l=[1,2,3,4,5]
print("initial list",l)
l.insert(2,10)
print("after inserting 10 at index 2",l)
l.remove(3)
print("after removing 3",l) 
l.append(6)
print("after appending 6",l)   
print('The length of the list is:',len(l))
popped= l.pop()
print("after popping last element",l)
print("popped element:", popped)
l.clear()
print("after clearing the list",l)